using Xunit;

namespace ControlPCIA.Tests;

public sealed class InventarioAplicacionesTests
{
    private static readonly AplicacionInstalada[] Aplicaciones =
    [
        new(
            "Cubase 15",
            "{PROGRAMFILES}\\Steinberg\\Cubase 15\\Cubase15.exe"),
        new(
            "Desinstalar Cubase",
            "Microsoft.AutoGenerated.UninstallCubase"),
        new(
            "Microsoft Edge",
            "MSEdge"),
        new(
            "Notepad++",
            "{PROGRAMFILES}\\Notepad++\\notepad++.exe")
    ];

    [Fact]
    public void Encuentra_la_aplicacion_real_sin_incluir_desinstaladores()
    {
        IReadOnlyList<AplicacionInstalada> candidatas =
            InventarioAplicaciones.SeleccionarCandidatas(
                "abre Cubase",
                Aplicaciones);

        AplicacionInstalada candidata = Assert.Single(candidatas);
        Assert.Equal("Cubase 15", candidata.Nombre);
    }

    [Fact]
    public void Tolera_una_variacion_corta_del_nombre()
    {
        IReadOnlyList<AplicacionInstalada> candidatas =
            InventarioAplicaciones.SeleccionarCandidatas(
                "inicia Cubaze",
                Aplicaciones);

        AplicacionInstalada candidata = Assert.Single(candidatas);
        Assert.Equal("Cubase 15", candidata.Nombre);
    }

    [Fact]
    public void No_inventa_candidatas_para_una_peticion_no_relacionada()
    {
        IReadOnlyList<AplicacionInstalada> candidatas =
            InventarioAplicaciones.SeleccionarCandidatas(
                "qué temperatura hace",
                Aplicaciones);

        Assert.Empty(candidatas);
    }
}
